;;; Plasma — animated sine-wave color field
(define w (canvas-width))
(define h (canvas-height))

(define block 8)
(define cols (quotient w block))
(define rows (quotient h block))

(define time 0.0)
(define gx 0)
(define gy 0)
(define px 0)
(define py 0)
(define v 0.0)
(define r 0)
(define g 0)
(define b 0)

(define (col-loop)
  (when (< gx cols)
    (set! px (* gx block))
    (set! py (* gy block))
    (set! v (+ (sin (+ (* px 0.04) time))
               (sin (+ (* py 0.05) (* time 1.3)))
               (sin (+ (* (+ px py) 0.03) (* time 0.7)))
               (sin (* (sqrt (+ (* px px) (* py py))) 0.04))))
    (set! r (floor (+ 128 (* 127 (sin (* v 3.14159))))))
    (set! g (floor (+ 128 (* 127 (sin (+ (* v 3.14159) 2.094))))))
    (set! b (floor (+ 128 (* 127 (sin (+ (* v 3.14159) 4.189))))))
    (canvas-set-fill-color r g b)
    (canvas-fill-rect px py block block)
    (set! gx (+ gx 1))
    (col-loop)))

(define (row-loop)
  (when (< gy rows)
    (set! gx 0)
    (col-loop)
    (set! gy (+ gy 1))
    (row-loop)))

(define (animate)
  (set! gy 0)
  (row-loop)
  (set! time (+ time 0.1))
  (yield)
  (animate))

(animate)
