;;; Plasma — animated sine-wave color field
(define w (canvas-width))
(define h (canvas-height))

(define block 4)
(define cols (/ w block))
(define rows (/ h block))

(define time 0.0)
(define gx 0)
(define gy 0)
(define px 0)
(define py 0)
(define v 0.0)
(define r 0)
(define g 0)
(define b 0)

(define (plasma-value x y t)
  (+ (sin (+ (* x 0.05) t))
     (sin (+ (* y 0.07) (* t 1.3)))
     (sin (+ (* (+ x y) 0.04) (* t 0.7)))
     (sin (+ (* (- (* x 0.03) (* y 0.02)) 2.0) (* t 0.5)))))

(define (draw-frame)
  (set! gy 0)
  (define (row-loop)
    (when (< gy rows)
      (set! gx 0)
      (define (col-loop)
        (when (< gx cols)
          (set! px (* gx block))
          (set! py (* gy block))
          (set! v (plasma-value px py time))
          (set! r (floor (+ 128 (* 127 (sin (* v 3.14159))))))
          (set! g (floor (+ 128 (* 127 (sin (+ (* v 3.14159) 2.094))))))
          (set! b (floor (+ 128 (* 127 (sin (+ (* v 3.14159) 4.189))))))
          (canvas-set-fill-color r g b)
          (canvas-fill-rect px py block block)
          (set! gx (+ gx 1))
          (col-loop)))
      (col-loop)
      (set! gy (+ gy 1))
      (row-loop)))
  (row-loop))

(define (animate)
  (draw-frame)
  (set! time (+ time 0.1))
  (yield)
  (animate))

(animate)
