;;; Plasma — animated sine-wave color field
(define w (canvas-width))
(define h (canvas-height))

(define block 8)
(define cols (quotient w block))
(define rows (quotient h block))

(define time 0.0)
(define gx 0)
(define gy 0)
(define px 0)
(define py 0)
(define v 0.0)
(define r 0)
(define g 0)
(define b 0)

(define (col-loop)
  (when (< gx cols)
    (set! px (* gx block))
    (set! py (* gy block))
    (set! v (+ (sin (+ (* px 0.04) (* py 0.03) time))
               (sin (+ (* px 0.03) (* py 0.05) (* time 1.3)))))
    ;; Map v (range ~-2..2) to RGB without extra sin calls
    (set! r (modulo (floor (+ 128 (* v 60))) 256))
    (set! g (modulo (floor (+ 128 (* v 80) (* time 40))) 256))
    (set! b (modulo (floor (+ 200 (* v 50) (* time 20))) 256))
    (canvas-set-fill-color r g b)
    (canvas-fill-rect px py block block)
    (set! gx (+ gx 1))
    (col-loop)))

(define (row-loop)
  (when (< gy rows)
    (set! gx 0)
    (col-loop)
    (set! gy (+ gy 1))
    (row-loop)))

(define (animate)
  (set! gy 0)
  (row-loop)
  (set! time (+ time 0.1))
  (yield)
  (animate))

(animate)
