;;; run.lisp — Boot ECE and run the app bundle.
;;; Generated by ece-build. Run with: sbcl --load run.lisp

;; Determine the directory containing this file
(defvar *dist-dir*
  (make-pathname :name nil :type nil :defaults *load-truename*))

;; Register this directory with ASDF so runtime.lisp can find bootstrap/
(require :asdf)
(push *dist-dir* asdf:*central-registry*)

;; Load the ECE runtime (boots from bootstrap/*.ecec automatically)
(asdf:load-system :ece)

;; Load and execute the app bundle
(ece::load-ecec-file (merge-pathnames "app.ecec" *dist-dir*))
