;;; WASM Test Runner — calls thunks directly (no try-eval)
(define (run-tests)
  (define total (length *tests*))
  (display "Running ")
  (display total)
  (display " tests...")
  (newline)
  (newline)
  (for-each
   (lambda (entry)
     (define name (car entry))
     (define thunk (cadr entry))
     (display "  ")
     (display name)
     (newline)
     (thunk))
   *tests*)
  (newline)
  (display *test-passes*)
  (display " passed, ")
  (display *test-failures*)
  (display " failed")
  (newline)
  (= *test-failures* 0))
