#!/bin/bash
# Build sandbox assets: embed WASM + .ecec as base64 in JS files
set -e

SANDBOX_DIR="sandbox"
WASM_FILE="wasm/runtime.wasm"
BOOTSTRAP_DIR="bootstrap"
GLUE_FILE="wasm/glue.js"

mkdir -p .tmp
echo "Building sandbox assets..."

# 1. Build WASM if needed
if [ ! -f "$WASM_FILE" ]; then
  make wasm
fi

# 2. Embed runtime.wasm + glue.js into ece-runtime.js
echo "// ECE Runtime — auto-generated by build-sandbox.sh" > "$SANDBOX_DIR/ece-runtime.js"
echo "// Contains runtime.wasm (base64) and glue.js" >> "$SANDBOX_DIR/ece-runtime.js"
echo "" >> "$SANDBOX_DIR/ece-runtime.js"

# Inline primitives.json as a JS variable (before glue.js uses it)
echo -n "const ECE_PRIMITIVES = " >> "$SANDBOX_DIR/ece-runtime.js"
cat wasm/primitives.json >> "$SANDBOX_DIR/ece-runtime.js"
echo ";" >> "$SANDBOX_DIR/ece-runtime.js"

# Inline glue.js (remove Node.js module.exports, replace require with inline var)
sed -e '/module\.exports/d' -e 's/require("\.\/primitives\.json")/ECE_PRIMITIVES/' "$GLUE_FILE" >> "$SANDBOX_DIR/ece-runtime.js"

echo "" >> "$SANDBOX_DIR/ece-runtime.js"
echo "// runtime.wasm as base64" >> "$SANDBOX_DIR/ece-runtime.js"
echo -n "const ECE_WASM_BASE64 = \"" >> "$SANDBOX_DIR/ece-runtime.js"
base64 -i "$WASM_FILE" | tr -d '\n' >> "$SANDBOX_DIR/ece-runtime.js"
echo "\";" >> "$SANDBOX_DIR/ece-runtime.js"

# 3. Embed bootstrap .ecec files (text, base64-encoded) into ece-bootstrap.js
echo "// ECE Bootstrap — auto-generated by build-sandbox.sh" > "$SANDBOX_DIR/ece-bootstrap.js"
echo "const ECE_BOOTSTRAP = {};" >> "$SANDBOX_DIR/ece-bootstrap.js"

for name in prelude compiler reader assembler compilation-unit browser-lib; do
  echo -n "ECE_BOOTSTRAP[\"$name\"] = \"" >> "$SANDBOX_DIR/ece-bootstrap.js"
  base64 -i "$BOOTSTRAP_DIR/$name.ecec" | tr -d '\n' >> "$SANDBOX_DIR/ece-bootstrap.js"
  echo "\";" >> "$SANDBOX_DIR/ece-bootstrap.js"
done

# 4. Pre-compile canned programs to .ecec and embed
echo "Compiling canned programs..."
echo "// Pre-compiled ECE programs — auto-generated" > "$SANDBOX_DIR/ece-compiled.js"
echo "const ECE_COMPILED = {};" >> "$SANDBOX_DIR/ece-compiled.js"

# Hello World
cat > .tmp/ece-hello.scm << 'EOFSCM'
(display "Hello, World!")
(newline)
EOFSCM
qlot exec sbcl --eval '(asdf:load-system :ece)' \
  --eval '(ece:evaluate (list (intern "compile-file" :ece) ".tmp/ece-hello.scm"))' \
  --quit 2>/dev/null

echo -n 'ECE_COMPILED["Hello World"] = "' >> "$SANDBOX_DIR/ece-compiled.js"
base64 -i .tmp/ece-hello.ecec | tr -d '\n' >> "$SANDBOX_DIR/ece-compiled.js"
echo '";' >> "$SANDBOX_DIR/ece-compiled.js"

echo "Sandbox assets built in $SANDBOX_DIR/"
