#!/bin/bash
# Build sandbox assets: embed WASM + .ececb as base64 in JS files
set -e

SANDBOX_DIR="sandbox"
WASM_FILE="wasm/runtime.wasm"
BOOTSTRAP_DIR="bootstrap"
GLUE_FILE="wasm/glue.js"

echo "Building sandbox assets..."

# 1. Build WASM if needed
if [ ! -f "$WASM_FILE" ]; then
  make wasm
fi

# 2. Embed runtime.wasm + glue.js into ece-runtime.js
echo "// ECE Runtime — auto-generated by build-sandbox.sh" > "$SANDBOX_DIR/ece-runtime.js"
echo "// Contains runtime.wasm (base64) and glue.js" >> "$SANDBOX_DIR/ece-runtime.js"
echo "" >> "$SANDBOX_DIR/ece-runtime.js"

# Inline glue.js (remove the Node.js module.exports line)
sed '/module\.exports/d' "$GLUE_FILE" >> "$SANDBOX_DIR/ece-runtime.js"

echo "" >> "$SANDBOX_DIR/ece-runtime.js"
echo "// runtime.wasm as base64" >> "$SANDBOX_DIR/ece-runtime.js"
echo -n "const ECE_WASM_BASE64 = \"" >> "$SANDBOX_DIR/ece-runtime.js"
base64 -i "$WASM_FILE" | tr -d '\n' >> "$SANDBOX_DIR/ece-runtime.js"
echo "\";" >> "$SANDBOX_DIR/ece-runtime.js"

# 3. Embed bootstrap .ececb files into ece-bootstrap.js
echo "// ECE Bootstrap — auto-generated by build-sandbox.sh" > "$SANDBOX_DIR/ece-bootstrap.js"
echo "const ECE_BOOTSTRAP = {};" >> "$SANDBOX_DIR/ece-bootstrap.js"

for name in prelude compiler reader assembler compilation-unit browser-lib; do
  echo -n "ECE_BOOTSTRAP[\"$name\"] = \"" >> "$SANDBOX_DIR/ece-bootstrap.js"
  base64 -i "$BOOTSTRAP_DIR/$name.ececb" | tr -d '\n' >> "$SANDBOX_DIR/ece-bootstrap.js"
  echo "\";" >> "$SANDBOX_DIR/ece-bootstrap.js"
done

# 4. Pre-compile canned programs to .ececb and embed
echo "Compiling canned programs..."
echo "// Pre-compiled ECE programs — auto-generated" > "$SANDBOX_DIR/ece-compiled.js"
echo "const ECE_COMPILED = {};" >> "$SANDBOX_DIR/ece-compiled.js"

# Hello World
cat > /tmp/ece-hello.scm << 'EOFSCM'
(display "Hello, World!")
(newline)
EOFSCM
qlot exec sbcl --eval '(asdf:load-system :ece)' \
  --eval '(ece:evaluate (list (intern "compile-file" :ece) "/tmp/ece-hello.scm"))' \
  --eval '(ece:evaluate (list (quote load) "src/ecec-to-binary.scm"))' \
  --eval '(ece::convert-ecec-to-ececb "/tmp/ece-hello.ecec" "/tmp/ece-hello.ececb")' \
  --quit 2>/dev/null

echo -n 'ECE_COMPILED["Hello World"] = "' >> "$SANDBOX_DIR/ece-compiled.js"
base64 -i /tmp/ece-hello.ececb | tr -d '\n' >> "$SANDBOX_DIR/ece-compiled.js"
echo '";' >> "$SANDBOX_DIR/ece-compiled.js"

echo "Sandbox assets built in $SANDBOX_DIR/"
